enum AppStatusEnum {
  PRODUCTION = 'PRODUCTION',
  DRAFT = 'DRAFT',
  TESTING = 'TESTING',
  REVIEW = 'REVIEW',
  REJECTED = 'REJECTED',
  PREVIOUS = 'PREVIOUS'
}

enum AppCategoryEnum {
  APPS_TO_SMARTWATCH = 'APPS_TO_SMARTWATCH',
  ART_AND_DESIGN = 'ART_AND_DESIGN',
  BEAUTY = 'BEAUTY',
  LIBRARIES_AND_DEMOS = 'LIBRARIES_AND_DEMOS',
  HOUSES_AND_DECORATION = 'HOUSES_AND_DECORATION',
  WEATHER = 'WEATHER',
  EAT_AND_DRINK = 'EAT_AND_DRINK',
  SHOPPING = 'SHOPPING',
  COMMUNICATION = 'COMMUNICATION',
  PHOTOGRAPHY = 'PHOTOGRAPHY',
  HUMOR = 'HUMOR',
  BOOKS_AND_REFERENCE = 'BOOKS_AND_REFERENCE',
  MAPS_AND_NAVIGATION = 'MAPS_AND_NAVIGATION',
  MEDICINE = 'MEDICINE',
  WATCH_FACES = 'WATCH_FACES',
  MUSIC_AND_AUDIO = 'MUSIC_AND_AUDIO',
  NEWS_AND_MAGAZINES = 'NEWS_AND_MAGAZINES',
  CUSTOMIZATION = 'CUSTOMIZATION'
}

export {
  AppCategoryEnum,
  AppStatusEnum
}
