enum TypeEnableEnum {
  ALWAYS = 'ALWAYS',
  PERIOD = 'PERIOD',
  AFTER_CLASS = 'AFTER_CLASS',
  AFTER_CLASS_PERIOD = 'AFTER_CLASS_PERIOD',
  AFTER_COURSE = 'AFTER_COURSE',
  AFTER_COURSE_PERIOD = 'AFTER_COURSE_PERIOD'
}

export {
  TypeEnableEnum
}
